title: Lubos Mudrak
description: >-
  I try not to break things these days

email: mudrak.lubos@gmail.com
author: Lubos Mudrak
twitter_username: lupajz
github_username: lupajz

theme: minima
show_excerpts: true
permalink: /blog/:year/:month/:day/:title
timezone: Europe/Prague
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  