blog_title: Only moderately interesting posts
description: >-
  I try not to break things these days

email: mudrak.lubos@gmail.com
author: Lubos Mudrak
twitter_username: lupajz
github_username: lupajz

google_analytics: UA-136686526-1

theme: minima
show_excerpts: true
permalink: /blog/:year/:month/:day/:title
timezone: Europe/Prague
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  